version: 1.0.0
name: cloudflare-argo-tunnel
slug: cloudflare-argo-tunnel
description: Cloudflare Argo Tunnel
url: https://github.com/duylnk68/hassio-smart-cctv
startup: application
arch:
  - armv7
boot: auto
options:
  url: http://supervisor:8123
  account_tag:
  tunnel_id:
  tunnel_name:
  tunnel_secret:
schema:
  url: str
  account_tag: str
  tunnel_id: str
  tunnel_name: str
  tunnel_secret: str