{
  "name": "cloudflare-argo-tunnel",
  "version": "1.0.0",
  "slug": "cloudflare-argo-tunnel",
  "description": "Cloudflare Argo Tunnel",
  "url": "https://github.com/duylnk68/hassio-smart-cctv",
  "startup": "application",
  "arch": [
    "aarch64",
    "amd64",
    "armhf",
    "i386"
  ],
  "boot": "auto",
  "options": {
    "log_level": "info",
    "seconds_between_quotes": 5
  },
  "schema": {
    "log_level": "match(^(trace|debug|info|notice|warning|error|fatal)$)",
    "seconds_between_quotes": "int(1,120)"
  }
}